# docker debian image
FROM debian:latest

## Standard python environment
# first line for any debian-based linux distros update and install apt-transport-https
RUN apt update && apt install -y apt-transport-https && apt upgrade -y